name: Terraform Apply or Destroy Secure S3

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action to perform: apply or destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials via OIDC
      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::975050234474:role/github-openid-demo1
          role-session-name: github-actions-terraform-${{ github.run_id }}
          aws-region: ap-south-1

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # Step 4: Terraform Init
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      # Step 5: Terraform Validate
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      # Step 7: Terraform Apply or Destroy (based on input)
      - name: Terraform Apply or Destroy
        working-directory: ./terraform
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "🟢 Running Terraform Apply..."
            terraform apply -auto-approve -input=false
          else
            echo "🔴 Running Terraform Destroy..."
            terraform destroy -auto-approve -input=false
          fi
